import { SupportedLanguage } from './types';

export const translations: Record<SupportedLanguage, Record<string, string>> = {
  fr: {
    'home': 'Accueil',
    'catalog': 'Catalogue',
    'about': 'À propos',
    'contact': 'Contact',
    'login': 'Connexion',
    'register': 'S\'inscrire',
    'logout': 'Déconnexion',
    'my_account': 'Mon Compte',
    'artist_tagline': "Melissa Pelussi - Artiste Contemporaine",
    'explore_catalog': "Explorer le Catalogue",
    'featured_gallery': "Galerie en vedette",
    'view_details': "Voir les détails",
    'by_artist': "par Melissa Pelussi",
    'available': 'Disponible',
    'sold': 'Vendu',
    'made_to_order': 'Sur commande',
    'add_to_cart': 'Ajouter au panier',
    'added_to_cart': 'Ajouté au panier!',
    'all_categories': 'Toutes catégories',
    'paintings': 'Peintures',
    'jewelry': 'Bijoux',
    'digital_art': 'Art Numérique',
    'prints': 'Impressions',
    'filter_by_category': 'Filtrer par catégorie',
    'about_artist_title': 'À propos de l\'artiste',
    'about_artist_home_title': "À propos de l'artiste",
    'about_artist_home_text': "Née avec une passion innée pour la couleur et la forme, Meeh a développé un style distinctif qui capture l'essence de l'esthétique européenne moderne...",
    'read_more': "Lire la suite",
    'art_categories': "Catégories d'Art",
    'newsletter_title': "Abonnez-vous à notre newsletter",
    'newsletter_text': "Recevez des mises à jour sur les nouvelles œuvres, les expositions et les offres exclusives.",
    'subscribe': "S'abonner",
    'email_placeholder': "Votre adresse e-mail",
    'artist_name': 'Melissa Pelussi',
    'artist_known_as': 'Meeh',
    'artist_location': 'Luxembourg',
    'biography_title': 'Biographie',
    'temp_bio_1': "Melissa Pelussi, connue dans le monde de l'art sous le nom de Meeh, est une artiste contemporaine basée au Luxembourg dont le travail jette un pont entre les médiums traditionnels et numériques. Née avec une passion innée pour la couleur et la forme, Meeh a développé un style distinctif qui capture l'essence de l'esthétique européenne moderne tout en rendant hommage aux traditions artistiques classiques.",
    'temp_bio_2': "Son parcours artistique a commencé par la peinture, où elle a exploré l'interaction de la lumière et de l'ombre à travers l'huile et l'acrylique. Au fil des ans, son expression créative s'est étendue à la conception de bijoux, où chaque pièce devient une sculpture portable, et à l'art numérique, où elle repousse les limites de la technologie et de l'imagination.",
    'temp_bio_3': "Le travail de Meeh a été exposé dans des galeries à travers l'Europe, les collectionneurs appréciant sa capacité unique à insuffler une profondeur émotionnelle profonde aux objets et scènes du quotidien. Chaque pièce raconte une histoire, invitant les spectateurs à découvrir leurs propres interprétations et connexions.",
    'temp_bio_4': "Actuellement basée au Luxembourg, Meeh continue de créer des œuvres qui remettent en question les perceptions et célèbrent la beauté trouvée dans les mondes tangible et numérique. Son atelier sert de sanctuaire créatif où les idées se transforment en expériences visuelles époustouflantes.",
    'artist_quote': "L'art n'est pas ce que vous voyez, mais ce que vous faites voir aux autres.",
    'artistic_statement_title': "Ma Philosophie",
    'artistic_journey_title': "Parcours Artistique",
    'view_my_artwork': "Voir mes œuvres",
    'get_in_touch': "Prendre contact",
    'contact_form_title': "Contactez-nous",
    'full_name': "Nom complet",
    'email_address': "Adresse e-mail",
    'phone_number': "Numéro de téléphone",
    'subject': "Sujet",
    'message': "Message",
    'send_message': "Envoyer le message",
    'contact_info': "Informations de contact",
    'faq_title': "Questions fréquentes",
    'faq_q1': "Combien de temps prend la livraison ?",
    'faq_q2': "Acceptez-vous les commandes personnalisées ?",
    'faq_q3': "Puis-je visiter l'atelier ?",
    'faq_q4': "Quels moyens de paiement acceptez-vous ?",
    'faq_q5': "Livrez-vous à l'international ?",
    'contact_form_success': "Message envoyé ! Nous vous répondrons dans les 24 heures.",
    'shopping_cart': "Panier d'achat",
    'your_cart_is_empty': "Votre panier est vide.",
    'browse_catalog': "Parcourir le catalogue",
    'order_summary': "Résumé de la commande",
    'subtotal': "Sous-total",
    'shipping': "Livraison",
    'calculate_shipping': "Calculer la livraison",
    'total': "Total",
    'proceed_to_checkout': "Passer à la caisse",
    'remove_item': "Retirer l'article",
    'quantity': "Quantité",
    'password': "Mot de passe",
    'confirm_password': "Confirmer le mot de passe",
    'already_have_account': "Vous avez déjà un compte ?",
    'dont_have_account': "Vous n'avez pas de compte ?",
    'login_to_account': "Connectez-vous à votre compte",
    'create_your_account': "Créez votre compte",
    'login_with_google': "Continuer avec Google",
    'or': "OU",
    'logged_in_successfully': "Connecté avec succès!",
    'registered_successfully': "Inscrit avec succès! Veuillez vérifier votre email.",
    'logged_out_successfully': "Déconnecté avec succès.",
    'auth_error_weak_password': "Le mot de passe doit comporter au moins 6 caractères.",
    'auth_error_email_exists': "Cette adresse e-mail est déjà utilisée.",
    'auth_error_invalid_credentials': "Email ou mot de passe invalide.",
    'auth_error_generic': "Une erreur s'est produite. Veuillez réessayer.",
    'welcome_back': "Bienvenue,",
    'checkout': 'Paiement',
    'dashboard': 'Tableau de bord',
    'shipping_address': 'Adresse de livraison',
    'payment_method': 'Moyen de paiement',
    'review_confirm': 'Vérifier et Confirmer',
    'continue_to_payment': 'Continuer vers le paiement',
    'place_order': 'Passer la commande',
    'order_confirmation': 'Confirmation de commande',
    'thank_you_for_order': 'Merci pour votre commande !',
    'order_number': 'Numéro de commande',
    'continue_shopping': 'Continuer vos achats',
    'my_orders': 'Mes commandes',
    'my_addresses': 'Mes adresses',
    'my_wishlist': 'Ma liste de souhaits',
    'overview': 'Aperçu',
    'date': 'Date',
    'status': 'Statut',
    'order_details': 'Détails de la commande',
    'add_new_address': 'Ajouter une nouvelle adresse',
    'edit_address': 'Modifier l\'adresse',
    'delete_address': 'Supprimer l\'adresse',
    'set_as_default': 'Définir par défaut',
    'default': 'Défaut',
    'recipient_name': 'Nom du destinataire',
    'address_line_1': 'Ligne d\'adresse 1',
    'address_line_2': 'Ligne d\'adresse 2 (Optionnel)',
    'city': 'Ville',
    'postal_code': 'Code Postal',
    'country': 'Pays',
    'save_address': 'Enregistrer l\'adresse',
    'cancel': 'Annuler',
    'address_saved': 'Adresse enregistrée avec succès.',
    'address_deleted': 'Adresse supprimée avec succès.',
    'error_saving_address': 'Erreur lors de l\'enregistrement de l\'adresse.',
    'error_deleting_address': 'Erreur lors de la suppression de l\'adresse.',
    'confirm_delete_address': 'Êtes-vous sûr de vouloir supprimer cette adresse ?',
    'no_orders_found': 'Aucune commande trouvée.',
    'no_addresses_found': 'Aucune adresse trouvée.',
    'total_orders': 'Commandes totales',
    'total_spent': 'Total dépensé',
    'active_orders': 'Commandes actives',
    'add_to_wishlist': 'Ajouter à la liste de souhaits',
    'remove_from_wishlist': 'Retirer de la liste de souhaits',
    'added_to_wishlist': 'Ajouté à la liste de souhaits!',
    'removed_from_wishlist': 'Retiré de la liste de souhaits.',
    'your_wishlist_is_empty': 'Votre liste de souhaits est vide.',
    'start_adding_items': 'Commencez par ajouter les articles que vous aimez.',
    'order_items': 'Articles de la commande',
    'price': 'Prix',
    'shipped_to': 'Expédié à',
    'order_not_found': 'Commande non trouvée.',
    'view_order_details': 'Voir les détails',
    'chatbot_title': 'Assistant d\'Art',
    'chatbot_greeting': 'Bonjour! Comment puis-je vous aider aujourd\'hui?',
    'chatbot_placeholder': 'Posez votre question...',
    'chatbot_send': 'Envoyer',
    'chatbot_header_title': 'Meeh - Assistant d\'Art',
    'chatbot_close_button_aria': 'Fermer le chat',
    'chatbot_typing': 'L\'assistant écrit...',
    'chatbot_user_alt': 'Utilisateur',
    'chatbot_bot_alt': 'Assistant d\'Art',
    'chatbot_send_button_aria': 'Envoyer le message',
    'chatbot_open_button_aria': 'Ouvrir le chat'
  },
  en: {
    'home': 'Home',
    'catalog': 'Catalog',
    'about': 'About',
    'contact': 'Contact',
    'login': 'Login',
    'register': 'Register',
    'logout': 'Logout',
    'my_account': 'My Account',
    'artist_tagline': "Melissa Pelussi - Contemporary Artist",
    'explore_catalog': "Explore Full Catalog",
    'featured_gallery': "Featured Gallery",
    'view_details': "View Details",
    'by_artist': "by Melissa Pelussi",
    'available': 'Available',
    'sold': 'Sold',
    'made_to_order': 'Made to Order',
    'add_to_cart': 'Add to Cart',
    'added_to_cart': 'Added to cart!',
    'all_categories': 'All Categories',
    'paintings': 'Paintings',
    'jewelry': 'Jewelry',
    'digital_art': 'Digital Art',
    'prints': 'Prints',
    'filter_by_category': 'Filter by Category',
    'about_artist_title': 'About the Artist',
    'about_artist_home_title': "About the Artist",
    'about_artist_home_text': "Born with an innate passion for color and form, Meeh has developed a distinctive style that captures the essence of modern European aesthetics...",
    'read_more': "Read More",
    'art_categories': "Art Categories",
    'newsletter_title': "Subscribe to our Newsletter",
    'newsletter_text': "Receive updates on new artworks, exhibitions, and exclusive offers.",
    'subscribe': "Subscribe",
    'email_placeholder': "Your email address",
    'artist_name': 'Melissa Pelussi',
    'artist_known_as': 'Meeh',
    'artist_location': 'Luxembourg',
    'biography_title': 'Biography',
    'temp_bio_1': "Melissa Pelussi, known in the art world as Meeh, is a contemporary artist based in Luxembourg whose work bridges the gap between traditional and digital mediums. Born with an innate passion for color and form, Meeh has developed a distinctive style that captures the essence of modern European aesthetics while paying homage to classical artistic traditions.",
    'temp_bio_2': "Her artistic journey began with painting, where she explored the interplay of light and shadow through oil and acrylic. Over the years, her creative expression expanded to include jewelry design, where each piece becomes a wearable sculpture, and digital art, where she pushes the boundaries of technology and imagination.",
    'temp_bio_3': "Meeh's work has been featured in galleries across Europe, with collectors appreciating her unique ability to infuse everyday objects and scenes with profound emotional depth. Each piece tells a story, inviting viewers to discover their own interpretations and connections.",
    'temp_bio_4': "Currently based in Luxembourg, Meeh continues to create artwork that challenges perceptions and celebrates the beauty found in both the tangible and digital worlds. Her studio serves as a creative sanctuary where ideas transform into stunning visual experiences.",
    'artist_quote': "Art is not what you see, but what you make others see.",
    'artistic_statement_title': "My Philosophy",
    'artistic_journey_title': "Artistic Journey",
    'view_my_artwork': "View My Artwork",
    'get_in_touch': "Get in Touch",
    'contact_form_title': "Contact Us",
    'full_name': "Full Name",
    'email_address': "Email Address",
    'phone_number': "Phone Number",
    'subject': "Subject",
    'message': "Message",
    'send_message': "Send Message",
    'contact_info': "Contact Information",
    'faq_title': "Frequently Asked Questions",
    'faq_q1': "How long does shipping take?",
    'faq_q2': "Do you accept commissions?",
    'faq_q3': "Can I visit the studio?",
    'faq_q4': "What payment methods do you accept?",
    'faq_q5': "Do you ship internationally?",
    'contact_form_success': "Message sent! We'll respond within 24 hours.",
    'shopping_cart': "Shopping Cart",
    'your_cart_is_empty': "Your cart is empty.",
    'browse_catalog': "Browse Catalog",
    'order_summary': "Order Summary",
    'subtotal': "Subtotal",
    'shipping': "Shipping",
    'calculate_shipping': "Calculate Shipping",
    'total': "Total",
    'proceed_to_checkout': "Proceed to Checkout",
    'remove_item': "Remove item",
    'quantity': "Quantity",
    'password': "Password",
    'confirm_password': "Confirm Password",
    'already_have_account': "Already have an account?",
    'dont_have_account': "Don't have an account?",
    'login_to_account': "Login to your account",
    'create_your_account': "Create your account",
    'login_with_google': "Continue with Google",
    'or': "OR",
    'logged_in_successfully': "Logged in successfully!",
    'registered_successfully': "Registered successfully! Please verify your email.",
    'logged_out_successfully': "Logged out successfully.",
    'auth_error_weak_password': "Password should be at least 6 characters.",
    'auth_error_email_exists': "This email address is already in use.",
    'auth_error_invalid_credentials': "Invalid email or password.",
    'auth_error_generic': "An error occurred. Please try again.",
    'welcome_back': "Welcome back,",
    'checkout': 'Checkout',
    'dashboard': 'Dashboard',
    'shipping_address': 'Shipping Address',
    'payment_method': 'Payment Method',
    'review_confirm': 'Review & Confirm',
    'continue_to_payment': 'Continue to Payment',
    'place_order': 'Place Order',
    'order_confirmation': 'Order Confirmation',
    'thank_you_for_order': 'Thank you for your order!',
    'order_number': 'Order Number',
    'continue_shopping': 'Continue Shopping',
    'my_orders': 'My Orders',
    'my_addresses': 'My Addresses',
    'my_wishlist': 'My Wishlist',
    'overview': 'Overview',
    'date': 'Date',
    'status': 'Status',
    'order_details': 'Order Details',
    'add_new_address': 'Add New Address',
    'edit_address': 'Edit Address',
    'delete_address': 'Delete Address',
    'set_as_default': 'Set as Default',
    'default': 'Default',
    'recipient_name': 'Recipient Name',
    'address_line_1': 'Address Line 1',
    'address_line_2': 'Address Line 2 (Optional)',
    'city': 'City',
    'postal_code': 'Postal Code',
    'country': 'Country',
    'save_address': 'Save Address',
    'cancel': 'Cancel',
    'address_saved': 'Address saved successfully.',
    'address_deleted': 'Address deleted successfully.',
    'error_saving_address': 'Error saving address.',
    'error_deleting_address': 'Error deleting address.',
    'confirm_delete_address': 'Are you sure you want to delete this address?',
    'no_orders_found': 'No orders found.',
    'no_addresses_found': 'No addresses found.',
    'total_orders': 'Total Orders',
    'total_spent': 'Total Spent',
    'active_orders': 'Active Orders',
    'add_to_wishlist': 'Add to Wishlist',
    'remove_from_wishlist': 'Remove from Wishlist',
    'added_to_wishlist': 'Added to Wishlist!',
    'removed_from_wishlist': 'Removed from Wishlist.',
    'your_wishlist_is_empty': 'Your wishlist is empty.',
    'start_adding_items': 'Start by adding items you love.',
    'order_items': 'Order Items',
    'price': 'Price',
    'shipped_to': 'Shipped To',
    'order_not_found': 'Order not found.',
    'view_order_details': 'View Details',
    'chatbot_title': 'Art Assistant',
    'chatbot_greeting': 'Hello! How can I assist you today?',
    'chatbot_placeholder': 'Ask a question...',
    'chatbot_send': 'Send',
    'chatbot_header_title': 'Meeh - Art Assistant',
    'chatbot_close_button_aria': 'Close chat',
    'chatbot_typing': 'Assistant is typing...',
    'chatbot_user_alt': 'User',
    'chatbot_bot_alt': 'Art Assistant',
    'chatbot_send_button_aria': 'Send message',
    'chatbot_open_button_aria': 'Open chat'
  },
  de: {
    'home': 'Startseite',
    'catalog': 'Katalog',
    'about': 'Über',
    'contact': 'Kontakt',
    'login': 'Anmelden',
    'register': 'Registrieren',
    'logout': 'Abmelden',
    'my_account': 'Mein Konto',
    'artist_tagline': "Melissa Pelussi - Zeitgenössische Künstlerin",
    'explore_catalog': "Vollständigen Katalog entdecken",
    'featured_gallery': "Ausgewählte Galerie",
    'view_details': "Details anzeigen",
    'by_artist': "von Melissa Pelussi",
    'available': 'Verfügbar',
    'sold': 'Verkauft',
    'made_to_order': 'Auf Bestellung',
    'add_to_cart': 'In den Warenkorb',
    'added_to_cart': 'Zum Warenkorb hinzugefügt!',
    'all_categories': 'Alle Kategorien',
    'paintings': 'Gemälde',
    'jewelry': 'Schmuck',
    'digital_art': 'Digitale Kunst',
    'prints': 'Drucke',
    'filter_by_category': 'Nach Kategorie filtern',
    'about_artist_title': 'Über die Künstlerin',
    'about_artist_home_title': "Über die Künstlerin",
    'about_artist_home_text': "Geboren mit einer angeborenen Leidenschaft für Farbe und Form, hat Meeh einen unverwechselbaren Stil entwickelt, der die Essenz moderner europäischer Ästhetik einfängt...",
    'read_more': "Weiterlesen",
    'art_categories': "Kunstkategorien",
    'newsletter_title': "Abonnieren Sie unseren Newsletter",
    'newsletter_text': "Erhalten Sie Updates zu neuen Kunstwerken, Ausstellungen und exklusiven Angeboten.",
    'subscribe': "Abonnieren",
    'email_placeholder': "Ihre E-Mail-Adresse",
    'artist_name': 'Melissa Pelussi',
    'artist_known_as': 'Meeh',
    'artist_location': 'Luxemburg',
    'biography_title': 'Biografie',
    'temp_bio_1': "Melissa Pelussi, in der Kunstwelt als Meeh bekannt, ist eine zeitgenössische Künstlerin aus Luxemburg, deren Arbeit die Lücke zwischen traditionellen und digitalen Medien schließt. Geboren mit einer angeborenen Leidenschaft für Farbe und Form, hat Meeh einen unverwechselbaren Stil entwickelt, der die Essenz moderner europäischer Ästhetik einfängt und gleichzeitig den klassischen künstlerischen Traditionen huldigt.",
    'temp_bio_2': "Ihre künstlerische Reise begann mit der Malerei, wo sie das Zusammenspiel von Licht und Schatten durch Öl und Acryl erforschte. Im Laufe der Jahre erweiterte sich ihr kreativer Ausdruck auf Schmuckdesign, bei dem jedes Stück zu einer tragbaren Skulptur wird, und auf digitale Kunst, bei der sie die Grenzen von Technologie und Vorstellungskraft sprengt.",
    'temp_bio_3': "Meehs Arbeiten wurden in Galerien in ganz Europa ausgestellt, wobei Sammler ihre einzigartige Fähigkeit schätzen, alltäglichen Objekten und Szenen eine tiefe emotionale Tiefe zu verleihen. Jedes Stück erzählt eine Geschichte und lädt die Betrachter ein, ihre eigenen Interpretationen und Verbindungen zu entdecken.",
    'temp_bio_4': "Derzeit in Luxemburg ansässig, schafft Meeh weiterhin Kunstwerke, die Wahrnehmungen herausfordern und die Schönheit feiern, die sowohl in der greifbaren als auch in der digitalen Welt zu finden ist. Ihr Atelier dient als kreativer Zufluchtsort, an dem Ideen zu atemberaubenden visuellen Erlebnissen werden.",
    'artist_quote': "Kunst ist nicht das, was du siehst, sondern das, was du andere sehen lässt.",
    'artistic_statement_title': "Meine Philosophie",
    'artistic_journey_title': "Künstlerische Reise",
    'view_my_artwork': "Meine Kunstwerke ansehen",
    'get_in_touch': "Kontakt aufnehmen",
    'contact_form_title': "Kontaktieren Sie uns",
    'full_name': "Vollständiger Name",
    'email_address': "E-Mail-Adresse",
    'phone_number': "Telefonnummer",
    'subject': "Betreff",
    'message': "Nachricht",
    'send_message': "Nachricht senden",
    'contact_info': "Kontaktinformationen",
    'faq_title': "Häufig gestellte Fragen",
    'faq_q1': "Wie lange dauert der Versand?",
    'faq_q2': "Akzeptieren Sie Auftragsarbeiten?",
    'faq_q3': "Kann ich das Atelier besuchen?",
    'faq_q4': "Welche Zahlungsmethoden akzeptieren Sie?",
    'faq_q5': "Versenden Sie international?",
    'contact_form_success': "Nachricht gesendet! Wir werden innerhalb von 24 Stunden antworten.",
    'shopping_cart': "Warenkorb",
    'your_cart_is_empty': "Ihr Warenkorb ist leer.",
    'browse_catalog': "Katalog durchsuchen",
    'order_summary': "Bestellübersicht",
    'subtotal': "Zwischensumme",
    'shipping': "Versand",
    'calculate_shipping': "Versand berechnen",
    'total': "Gesamt",
    'proceed_to_checkout': "Zur Kasse gehen",
    'remove_item': "Artikel entfernen",
    'quantity': "Menge",
    'password': "Passwort",
    'confirm_password': "Passwort bestätigen",
    'already_have_account': "Haben Sie bereits ein Konto?",
    'dont_have_account': "Haben Sie kein Konto?",
    'login_to_account': "In Ihr Konto einloggen",
    'create_your_account': "Erstellen Sie Ihr Konto",
    'login_with_google': "Mit Google fortfahren",
    'or': "ODER",
    'logged_in_successfully': "Erfolgreich angemeldet!",
    'registered_successfully': "Erfolgreich registriert! Bitte bestätigen Sie Ihre E-Mail.",
    'logged_out_successfully': "Erfolgreich abgemeldet.",
    'auth_error_weak_password': "Das Passwort sollte mindestens 6 Zeichen lang sein.",
    'auth_error_email_exists': "Diese E-Mail-Adresse wird bereits verwendet.",
    'auth_error_invalid_credentials': "Ungültige E-Mail oder ungültiges Passwort.",
    'auth_error_generic': "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
    'welcome_back': "Willkommen zurück,",
    'checkout': 'Kasse',
    'dashboard': 'Dashboard',
    'shipping_address': 'Lieferadresse',
    'payment_method': 'Zahlungsmethode',
    'review_confirm': 'Überprüfen & Bestätigen',
    'continue_to_payment': 'Weiter zur Zahlung',
    'place_order': 'Bestellung aufgeben',
    'order_confirmation': 'Bestellbestätigung',
    'thank_you_for_order': 'Vielen Dank für Ihre Bestellung!',
    'order_number': 'Bestellnummer',
    'continue_shopping': 'Weiter einkaufen',
    'my_orders': 'Meine Bestellungen',
    'my_addresses': 'Meine Adressen',
    'my_wishlist': 'Meine Wunschliste',
    'overview': 'Übersicht',
    'date': 'Datum',
    'status': 'Status',
    'order_details': 'Bestelldetails',
    'add_new_address': 'Neue Adresse hinzufügen',
    'edit_address': 'Adresse bearbeiten',
    'delete_address': 'Adresse löschen',
    'set_as_default': 'Als Standard festlegen',
    'default': 'Standard',
    'recipient_name': 'Empfängername',
    'address_line_1': 'Adresszeile 1',
    'address_line_2': 'Adresszeile 2 (Optional)',
    'city': 'Stadt',
    'postal_code': 'Postleitzahl',
    'country': 'Land',
    'save_address': 'Adresse speichern',
    'cancel': 'Abbrechen',
    'address_saved': 'Adresse erfolgreich gespeichert.',
    'address_deleted': 'Adresse erfolgreich gelöscht.',
    'error_saving_address': 'Fehler beim Speichern der Adresse.',
    'error_deleting_address': 'Fehler beim Löschen der Adresse.',
    'confirm_delete_address': 'Möchten Sie diese Adresse wirklich löschen?',
    'no_orders_found': 'Keine Bestellungen gefunden.',
    'no_addresses_found': 'Keine Adressen gefunden.',
    'total_orders': 'Gesamtbestellungen',
    'total_spent': 'Gesamtausgaben',
    'active_orders': 'Aktive Bestellungen',
    'add_to_wishlist': 'Zur Wunschliste hinzufügen',
    'remove_from_wishlist': 'Von der Wunschliste entfernen',
    'added_to_wishlist': 'Zur Wunschliste hinzugefügt!',
    'removed_from_wishlist': 'Von der Wunschliste entfernt.',
    'your_wishlist_is_empty': 'Ihre Wunschliste ist leer.',
    'start_adding_items': 'Fügen Sie Artikel hinzu, die Ihnen gefallen.',
    'order_items': 'Bestellartikel',
    'price': 'Preis',
    'shipped_to': 'Versandt an',
    'order_not_found': 'Bestellung nicht gefunden.',
    'view_order_details': 'Details anzeigen',
    'chatbot_title': 'Kunst-Assistent',
    'chatbot_greeting': 'Hallo! Wie kann ich Ihnen heute helfen?',
    'chatbot_placeholder': 'Stellen Sie eine Frage...',
    'chatbot_send': 'Senden',
    'chatbot_header_title': 'Meeh - Kunst-Assistent',
    'chatbot_close_button_aria': 'Chat schließen',
    'chatbot_typing': 'Assistent tippt...',
    'chatbot_user_alt': 'Benutzer',
    'chatbot_bot_alt': 'Kunst-Assistent',
    'chatbot_send_button_aria': 'Nachricht senden',
    'chatbot_open_button_aria': 'Chat öffnen'
  },
  pt: {
    'home': 'Início',
    'catalog': 'Catálogo',
    'about': 'Sobre',
    'contact': 'Contato',
    'login': 'Entrar',
    'register': 'Registrar',
    'logout': 'Sair',
    'my_account': 'Minha Conta',
    'artist_tagline': "Melissa Pelussi - Artista Contemporânea",
    'explore_catalog': "Explorar Catálogo Completo",
    'featured_gallery': "Galeria em Destaque",
    'view_details': "Ver Detalhes",
    'by_artist': "por Melissa Pelussi",
    'available': 'Disponível',
    'sold': 'Vendido',
    'made_to_order': 'Feito sob Encomenda',
    'add_to_cart': 'Adicionar ao Carrinho',
    'added_to_cart': 'Adicionado ao carrinho!',
    'all_categories': 'Todas as Categorias',
    'paintings': 'Pinturas',
    'jewelry': 'Joias',
    'digital_art': 'Arte Digital',
    'prints': 'Impressões',
    'filter_by_category': 'Filtrar por Categoria',
    'about_artist_title': 'Sobre a Artista',
    'about_artist_home_title': "Sobre a Artista",
    'about_artist_home_text': "Nascida com uma paixão inata por cor e forma, Meeh desenvolveu um estilo distinto que captura a essência da estética europeia moderna...",
    'read_more': "Leia Mais",
    'art_categories': "Categorias de Arte",
    'newsletter_title': "Assine nossa Newsletter",
    'newsletter_text': "Receba atualizações sobre novas obras, exposições e ofertas exclusivas.",
    'subscribe': "Assinar",
    'email_placeholder': "Seu endereço de e-mail",
    'artist_name': 'Melissa Pelussi',
    'artist_known_as': 'Meeh',
    'artist_location': 'Luxemburgo',
    'biography_title': 'Biografia',
    'temp_bio_1': "Melissa Pelussi, conhecida no mundo da arte como Meeh, é uma artista contemporânea baseada em Luxemburgo cujo trabalho preenche a lacuna entre mídias tradicionais e digitais. Nascida com uma paixão inata por cor e forma, Meeh desenvolveu um estilo distinto que captura a essência da estética europeia moderna, prestando homenagem às tradições artísticas clássicas.",
    'temp_bio_2': "Sua jornada artística começou com a pintura, onde explorou a interação de luz e sombra através de óleo e acrílico. Ao longo dos anos, sua expressão criativa expandiu-se para incluir o design de joias, onde cada peça se torna uma escultura vestível, e a arte digital, onde ela ultrapassa os limites da tecnologia e da imaginação.",
    'temp_bio_3': "O trabalho de Meeh foi destaque em galerias por toda a Europa, com colecionadores apreciando sua capacidade única de infundir objetos e cenas do cotidiano com profunda profundidade emocional. Cada peça conta uma história, convidando os espectadores a descobrir suas próprias interpretações e conexões.",
    'temp_bio_4': "Atualmente baseada em Luxemburgo, Meeh continua a criar obras de arte que desafiam percepções e celebram a beleza encontrada tanto no mundo tangível quanto no digital. Seu estúdio serve como um santuário criativo onde ideias se transformam em experiências visuais deslumbrantes.",
    'artist_quote': "A arte não é o que você vê, mas o que você faz os outros verem.",
    'artistic_statement_title': "Minha Filosofia",
    'artistic_journey_title': "Jornada Artística",
    'view_my_artwork': "Ver Minhas Obras",
    'get_in_touch': "Entre em Contato",
    'contact_form_title': "Fale Conosco",
    'full_name': "Nome Completo",
    'email_address': "Endereço de E-mail",
    'phone_number': "Número de Telefone",
    'subject': "Assunto",
    'message': "Mensagem",
    'send_message': "Enviar Mensagem",
    'contact_info': "Informações de Contato",
    'faq_title': "Perguntas Frequentes",
    'faq_q1': "Quanto tempo leva o envio?",
    'faq_q2': "Você aceita encomendas?",
    'faq_q3': "Posso visitar o estúdio?",
    'faq_q4': "Quais métodos de pagamento vocês aceitam?",
    'faq_q5': "Vocês enviam para o exterior?",
    'contact_form_success': "Mensagem enviada! Responderemos em até 24 horas.",
    'shopping_cart': "Carrinho de Compras",
    'your_cart_is_empty': "Seu carrinho está vazio.",
    'browse_catalog': "Navegar no Catálogo",
    'order_summary': "Resumo do Pedido",
    'subtotal': "Subtotal",
    'shipping': "Envio",
    'calculate_shipping': "Calcular Envio",
    'total': "Total",
    'proceed_to_checkout': "Ir para o Checkout",
    'remove_item': "Remover item",
    'quantity': "Quantidade",
    'password': "Senha",
    'confirm_password': "Confirmar Senha",
    'already_have_account': "Já tem uma conta?",
    'dont_have_account': "Não tem uma conta?",
    'login_to_account': "Acesse sua conta",
    'create_your_account': "Crie sua conta",
    'login_with_google': "Continuar com o Google",
    'or': "OU",
    'logged_in_successfully': "Login efetuado com sucesso!",
    'registered_successfully': "Registrado com sucesso! Por favor, verifique seu e-mail.",
    'logged_out_successfully': "Logout efetuado com sucesso.",
    'auth_error_weak_password': "A senha deve ter pelo menos 6 caracteres.",
    'auth_error_email_exists': "Este endereço de e-mail já está em uso.",
    'auth_error_invalid_credentials': "E-mail ou senha inválidos.",
    'auth_error_generic': "Ocorreu um erro. Por favor, tente novamente.",
    'welcome_back': "Bem-vindo(a) de volta,",
    'checkout': 'Checkout',
    'dashboard': 'Painel',
    'shipping_address': 'Endereço de Entrega',
    'payment_method': 'Método de Pagamento',
    'review_confirm': 'Revisar e Confirmar',
    'continue_to_payment': 'Continuar para Pagamento',
    'place_order': 'Finalizar Pedido',
    'order_confirmation': 'Confirmação do Pedido',
    'thank_you_for_order': 'Obrigado pelo seu pedido!',
    'order_number': 'Número do Pedido',
    'continue_shopping': 'Continuar Comprando',
    'my_orders': 'Meus Pedidos',
    'my_addresses': 'Meus Endereços',
    'my_wishlist': 'Minha Lista de Desejos',
    'overview': 'Visão Geral',
    'date': 'Data',
    'status': 'Status',
    'order_details': 'Detalhes do Pedido',
    'add_new_address': 'Adicionar Novo Endereço',
    'edit_address': 'Editar Endereço',
    'delete_address': 'Excluir Endereço',
    'set_as_default': 'Definir como Padrão',
    'default': 'Padrão',
    'recipient_name': 'Nome do Destinatário',
    'address_line_1': 'Endereço Linha 1',
    'address_line_2': 'Endereço Linha 2 (Opcional)',
    'city': 'Cidade',
    'postal_code': 'Código Postal',
    'country': 'País',
    'save_address': 'Salvar Endereço',
    'cancel': 'Cancelar',
    'address_saved': 'Endereço salvo com sucesso.',
    'address_deleted': 'Endereço excluído com sucesso.',
    'error_saving_address': 'Erro ao salvar o endereço.',
    'error_deleting_address': 'Erro ao excluir o endereço.',
    'confirm_delete_address': 'Tem certeza que deseja excluir este endereço?',
    'no_orders_found': 'Nenhum pedido encontrado.',
    'no_addresses_found': 'Nenhum endereço encontrado.',
    'total_orders': 'Total de Pedidos',
    'total_spent': 'Total Gasto',
    'active_orders': 'Pedidos Ativos',
    'add_to_wishlist': 'Adicionar à Lista de Desejos',
    'remove_from_wishlist': 'Remover da Lista de Desejos',
    'added_to_wishlist': 'Adicionado à Lista de Desejos!',
    'removed_from_wishlist': 'Removido da Lista de Desejos.',
    'your_wishlist_is_empty': 'Sua lista de desejos está vazia.',
    'start_adding_items': 'Comece adicionando itens que você ama.',
    'order_items': 'Itens do Pedido',
    'price': 'Preço',
    'shipped_to': 'Enviado Para',
    'order_not_found': 'Pedido não encontrado.',
    'view_order_details': 'Ver Detalhes',
    'chatbot_title': 'Assistente de Arte',
    'chatbot_greeting': 'Olá! Como posso ajudar hoje?',
    'chatbot_placeholder': 'Faça uma pergunta...',
    'chatbot_send': 'Enviar',
    'chatbot_header_title': 'Meeh - Assistente de Arte',
    'chatbot_close_button_aria': 'Fechar chat',
    'chatbot_typing': 'Assistente está a digitar...',
    'chatbot_user_alt': 'Utilizador',
    'chatbot_bot_alt': 'Assistente de Arte',
    'chatbot_send_button_aria': 'Enviar mensagem',
    'chatbot_open_button_aria': 'Abrir chat'
  },
};
