import { Product, Order, AddressWithId, Wishlist } from '@shared/types';

// Este arquivo simula seu banco de dados (Firestore).
// Criamos uma lista de produtos de exemplo com todos os detalhes, incluindo as traduções.
// Usamos isso para desenvolver e testar a aparência do site sem precisar conectar
// ao Firebase o tempo todo. As imagens são placeholders do serviço picsum.photos.

const toTimestamp = (dateString: string) => ({
  seconds: Math.floor(new Date(dateString).getTime() / 1000),
  nanoseconds: 0
});

export const mockProducts: Product[] = [
  {
    id: '1',
    categories: ['paintings'],
    translations: {
      fr: { title: "Rêverie Éthérée", description: "Une exploration abstraite des paysages de rêve, mêlant des bleus profonds et des ors scintillants.", materials: "Huile sur toile" },
      en: { title: "Ethereal Reverie", description: "An abstract exploration of dreamscapes, blending deep blues and shimmering golds.", materials: "Oil on canvas" },
      de: { title: "Ätherische Träumerei", description: "Eine abstrakte Erforschung von Traumlandschaften, die tiefe Blautöne und schimmernde Goldtöne mischt.", materials: "Öl auf Leinwand" },
      pt: { title: "Devaneio Etéreo", description: "Uma exploração abstrata de paisagens oníricas, misturando azuis profundos e dourados cintilantes.", materials: "Óleo sobre tela" },
    },
    cover_original: 'https://picsum.photos/id/101/800/800',
    cover_thumb: 'https://picsum.photos/id/101/400/400',
    gallery: [{ original: 'https://picsum.photos/id/101/800/800', thumb: 'https://picsum.photos/id/101/400/400', alt: 'Abstract painting with blue and gold' }],
    priceCents: 120000,
    currency: 'EUR',
    dimensions: { heightCm: 100, widthCm: 70, depthCm: 4 },
    weightKg: 5,
    status: 'available',
    stock: 1,
    isActive: true,
    tags: ['abstract', 'blue', 'gold', 'large'],
    slug: 'ethereal-reverie',
    featured: true,
    createdAt: toTimestamp('2023-10-26T10:00:00Z'),
    updatedAt: toTimestamp('2023-10-26T10:00:00Z'),
  },
  {
    id: '2',
    categories: ['jewelry'],
    translations: {
      fr: { title: "Pendentif 'Goutte de Lune'", description: "Un pendentif en argent sterling fait main avec une pierre de lune captivante.", materials: "Argent sterling, pierre de lune" },
      en: { title: "Moon-drop Pendant", description: "A handmade sterling silver pendant featuring a captivating moonstone.", materials: "Sterling silver, moonstone" },
      de: { title: "Mondtropfen-Anhänger", description: "Ein handgefertigter Anhänger aus Sterlingsilber mit einem faszinierenden Mondstein.", materials: "Sterlingsilber, Mondstein" },
      pt: { title: "Pingente Gota de Lua", description: "Um pingente de prata esterlina feito à mão com uma pedra da lua cativante.", materials: "Prata de lei, pedra da lua" },
    },
    cover_original: 'https://picsum.photos/id/201/800/800',
    cover_thumb: 'https://picsum.photos/id/201/400/400',
    gallery: [{ original: 'https://picsum.photos/id/201/800/800', thumb: 'https://picsum.photos/id/201/400/400', alt: 'Silver pendant with a moonstone' }],
    priceCents: 35000,
    currency: 'EUR',
    dimensions: { heightCm: 4, widthCm: 2, depthCm: 1 },
    weightKg: 0.1,
    status: 'available',
    stock: 5,
    isActive: true,
    tags: ['jewelry', 'silver', 'moonstone', 'handmade'],
    slug: 'moon-drop-pendant',
    featured: true,
    createdAt: toTimestamp('2024-01-15T14:30:00Z'),
    updatedAt: toTimestamp('2024-01-15T14:30:00Z'),
  },
  {
    id: '3',
    categories: ['digital'],
    translations: {
      fr: { title: "Néobloom Cybernétique", description: "Une pièce d'art numérique explorant la fusion de la nature et de la technologie.", materials: "Art numérique, impression giclée" },
      en: { title: "Cybernetic Neobloom", description: "A digital art piece exploring the fusion of nature and technology.", materials: "Digital art, giclée print" },
      de: { title: "Kybernetische Neublüte", description: "Ein digitales Kunstwerk, das die Verschmelzung von Natur und Technologie erforscht.", materials: "Digitale Kunst, Giclée-Druck" },
      pt: { title: "Neoflora Cibernética", description: "Uma peça de arte digital que explora a fusão da natureza com a tecnologia.", materials: "Arte digital, impressão giclée" },
    },
    cover_original: 'https://picsum.photos/id/301/800/800',
    cover_thumb: 'https://picsum.photos/id/301/400/400',
    gallery: [{ original: 'https://picsum.photos/id/301/800/800', thumb: 'https://picsum.photos/id/301/400/400', alt: 'Digital art of a futuristic flower' }],
    priceCents: 50000,
    currency: 'EUR',
    dimensions: { heightCm: 80, widthCm: 80 },
    weightKg: 2,
    status: 'madeToOrder',
    stock: 100,
    isActive: true,
    tags: ['digital', 'futuristic', 'nature', 'colorful'],
    slug: 'cybernetic-neobloom',
    featured: true,
    createdAt: toTimestamp('2024-02-20T11:00:00Z'),
    updatedAt: toTimestamp('2024-02-20T11:00:00Z'),
  },
  {
    id: '4',
    categories: ['paintings'],
    translations: {
      fr: { title: "Sérénité Urbaine", description: "Paysage urbain abstrait au crépuscule, capturant le calme au milieu du chaos.", materials: "Acrylique sur toile" },
      en: { title: "Urban Serenity", description: "Abstract cityscape at dusk, capturing the calm amidst the chaos.", materials: "Acrylic on canvas" },
      de: { title: "Urbane Gelassenheit", description: "Abstrakte Stadtlandschaft in der Dämmerung, die die Ruhe inmitten des Chaos einfängt.", materials: "Acryl auf Leinwand" },
      pt: { title: "Serenidade Urbana", description: "Paisagem urbana abstrata ao entardecer, capturando a calma em meio ao caos.", materials: "Acrílico sobre tela" },
    },
    cover_original: 'https://picsum.photos/id/402/800/800',
    cover_thumb: 'https://picsum.photos/id/402/400/400',
    gallery: [{ original: 'https://picsum.photos/id/402/800/800', thumb: 'https://picsum.photos/id/402/400/400', alt: 'Abstract cityscape painting' }],
    priceCents: 95000,
    currency: 'EUR',
    dimensions: { heightCm: 60, widthCm: 90, depthCm: 3 },
    weightKg: 4,
    status: 'sold',
    stock: 0,
    isActive: false,
    tags: ['cityscape', 'abstract', 'dusk', 'acrylic'],
    slug: 'urban-serenity',
    featured: false,
    createdAt: toTimestamp('2022-11-05T18:00:00Z'),
    updatedAt: toTimestamp('2023-05-10T12:00:00Z'),
  },
  {
    id: '5',
    categories: ['paintings'],
    translations: {
      fr: { title: "Murmures de la Forêt", description: "Une peinture texturée représentant la lumière filtrant à travers une canopée dense.", materials: "Techniques mixtes sur bois" },
      en: { title: "Forest Whispers", description: "A textured painting depicting light filtering through a dense canopy.", materials: "Mixed media on wood panel" },
      de: { title: "Waldgeflüster", description: "Ein strukturiertes Gemälde, das Licht darstellt, das durch ein dichtes Blätterdach filtert.", materials: "Mischtechnik auf Holz" },
      pt: { title: "Sussurros da Floresta", description: "Uma pintura texturizada que retrata a luz filtrando através de um denso dossel.", materials: "Técnica mista em painel de madeira" },
    },
    cover_original: 'https://picsum.photos/id/503/800/800',
    cover_thumb: 'https://picsum.photos/id/503/400/400',
    gallery: [{ original: 'https://picsum.photos/id/503/800/800', thumb: 'https://picsum.photos/id/503/400/400', alt: 'Painting of a forest canopy' }],
    priceCents: 150000,
    currency: 'EUR',
    dimensions: { heightCm: 120, widthCm: 80, depthCm: 5 },
    weightKg: 7,
    status: 'available',
    stock: 1,
    isActive: true,
    tags: ['forest', 'nature', 'light', 'textured'],
    slug: 'forest-whispers',
    featured: true,
    createdAt: toTimestamp('2023-03-12T09:20:00Z'),
    updatedAt: toTimestamp('2023-03-12T09:20:00Z'),
  },
  {
    id: '6',
    categories: ['prints'],
    translations: {
      fr: { title: "Impression 'Écho'", description: "Impression giclée en édition limitée de l'œuvre numérique 'Écho'.", materials: "Papier d'art Hahnemühle" },
      en: { title: "'Echo' Print", description: "Limited edition giclée print of the digital artwork 'Echo'.", materials: "Hahnemühle fine art paper" },
      de: { title: "'Echo' Druck", description: "Limitierte Giclée-Druckausgabe des digitalen Kunstwerks 'Echo'.", materials: "Hahnemühle Fine Art Papier" },
      pt: { title: "Impressão 'Eco'", description: "Impressão giclée de edição limitada da obra de arte digital 'Eco'.", materials: "Papel de belas artes Hahnemühle" },
    },
    cover_original: 'https://picsum.photos/id/604/800/800',
    cover_thumb: 'https://picsum.photos/id/604/400/400',
    gallery: [{ original: 'https://picsum.photos/id/604/800/800', thumb: 'https://picsum.photos/id/604/400/400', alt: 'Abstract digital art print' }],
    priceCents: 25000,
    currency: 'EUR',
    dimensions: { heightCm: 50, widthCm: 50 },
    weightKg: 1,
    status: 'available',
    stock: 50,
    isActive: true,
    tags: ['print', 'limited edition', 'giclee', 'abstract'],
    slug: 'echo-print',
    featured: false,
    createdAt: toTimestamp('2024-03-01T16:45:00Z'),
    updatedAt: toTimestamp('2024-03-01T16:45:00Z'),
  },
  // Add 6 more products to have 12 total for pagination
    {
    id: '7',
    categories: ['jewelry'],
    translations: {
      fr: { title: "Bague 'Spirale Solaire'", description: "Bague en or 18 carats avec un design en spirale, symbolisant l'énergie éternelle.", materials: "Or 18k" },
      en: { title: "'Solar Spiral' Ring", description: "An 18k gold ring with a spiral design, symbolizing eternal energy.", materials: "18k Gold" },
      de: { title: "'Sonnenspirale' Ring", description: "Ein 18-karätiger Goldring mit Spiraldesign, der ewige Energie symbolisiert.", materials: "18k Gold" },
      pt: { title: "Anel 'Espiral Solar'", description: "Anel em ouro 18k com design em espiral, simbolizando a energia eterna.", materials: "Ouro 18k" },
    },
    cover_original: 'https://picsum.photos/id/701/800/800',
    cover_thumb: 'https://picsum.photos/id/701/400/400',
    gallery: [{ original: 'https://picsum.photos/id/701/800/800', thumb: 'https://picsum.photos/id/701/400/400', alt: 'Gold spiral ring' }],
    priceCents: 85000,
    currency: 'EUR',
    dimensions: { heightCm: 2, widthCm: 2, depthCm: 0.5 },
    weightKg: 0.05,
    status: 'available',
    stock: 3,
    isActive: true,
    tags: ['jewelry', 'gold', 'ring', 'spiral'],
    slug: 'solar-spiral-ring',
    featured: true,
    createdAt: toTimestamp('2023-09-05T10:00:00Z'),
    updatedAt: toTimestamp('2023-09-05T10:00:00Z'),
  },
  {
    id: '8',
    categories: ['paintings'],
    translations: {
      fr: { title: "Horizon de Corail", description: "Une vue marine semi-abstraite avec des teintes chaudes de corail et de turquoise.", materials: "Aquarelle sur papier" },
      en: { title: "Coral Horizon", description: "A semi-abstract seascape with warm hues of coral and turquoise.", materials: "Watercolor on paper" },
      de: { title: "Korallenhorizont", description: "Eine halbabstrakte Seelandschaft mit warmen Korallen- und Türkistönen.", materials: "Aquarell auf Papier" },
      pt: { title: "Horizonte de Coral", description: "Uma paisagem marinha semi-abstrata com tons quentes de coral e turquesa.", materials: "Aquarela sobre papel" },
    },
    cover_original: 'https://picsum.photos/id/802/800/800',
    cover_thumb: 'https://picsum.photos/id/802/400/400',
    gallery: [{ original: 'https://picsum.photos/id/802/800/800', thumb: 'https://picsum.photos/id/802/400/400', alt: 'Watercolor seascape painting' }],
    priceCents: 60000,
    currency: 'EUR',
    dimensions: { heightCm: 40, widthCm: 60 },
    weightKg: 1.5,
    status: 'available',
    stock: 1,
    isActive: true,
    tags: ['watercolor', 'seascape', 'coral', 'turquoise'],
    slug: 'coral-horizon',
    featured: false,
    createdAt: toTimestamp('2023-07-21T15:10:00Z'),
    updatedAt: toTimestamp('2023-07-21T15:10:00Z'),
  },
   {
    id: '9',
    categories: ['digital'],
    translations: {
      fr: { title: "Géométrie Fractale", description: "Composition numérique complexe basée sur des motifs fractals et la géométrie sacrée.", materials: "Art numérique génératif" },
      en: { title: "Fractal Geometry", description: "A complex digital composition based on fractal patterns and sacred geometry.", materials: "Generative digital art" },
      de: { title: "Fraktale Geometrie", description: "Eine komplexe digitale Komposition basierend auf Fraktalmustern und heiliger Geometrie.", materials: "Generative digitale Kunst" },
      pt: { title: "Geometria Fractal", description: "Uma composição digital complexa baseada em padrões fractais e geometria sagrada.", materials: "Arte digital generativa" },
    },
    cover_original: 'https://picsum.photos/id/903/800/800',
    cover_thumb: 'https://picsum.photos/id/903/400/400',
    gallery: [{ original: 'https://picsum.photos/id/903/800/800', thumb: 'https://picsum.photos/id/903/400/400', alt: 'Fractal digital art' }],
    priceCents: 45000,
    currency: 'EUR',
    dimensions: { heightCm: 70, widthCm: 70 },
    weightKg: 2,
    status: 'madeToOrder',
    stock: 100,
    isActive: true,
    tags: ['digital', 'fractal', 'geometric', 'abstract'],
    slug: 'fractal-geometry',
    featured: false,
    createdAt: toTimestamp('2024-04-10T13:00:00Z'),
    updatedAt: toTimestamp('2024-04-10T13:00:00Z'),
  },
  {
    id: '10',
    categories: ['paintings'],
    translations: {
      fr: { title: "L'Étreinte du Silence", description: "Un portrait minimaliste capturant un moment d'introspection silencieuse.", materials: "Charbon de bois sur papier" },
      en: { title: "The Embrace of Silence", description: "A minimalist portrait capturing a moment of quiet introspection.", materials: "Charcoal on paper" },
      de: { title: "Die Umarmung der Stille", description: "Ein minimalistisches Porträt, das einen Moment stiller Einkehr festhält.", materials: "Kohle auf Papier" },
      pt: { title: "O Abraço do Silêncio", description: "Um retrato minimalista capturando um momento de introspecção silenciosa.", materials: "Carvão sobre papel" },
    },
    cover_original: 'https://picsum.photos/id/1011/800/800',
    cover_thumb: 'https://picsum.photos/id/1011/400/400',
    gallery: [{ original: 'https://picsum.photos/id/1011/800/800', thumb: 'https://picsum.photos/id/1011/400/400', alt: 'Charcoal portrait' }],
    priceCents: 75000,
    currency: 'EUR',
    dimensions: { heightCm: 70, widthCm: 50 },
    weightKg: 1.8,
    status: 'available',
    stock: 1,
    isActive: true,
    tags: ['portrait', 'charcoal', 'minimalist', 'black and white'],
    slug: 'embrace-of-silence',
    featured: true,
    createdAt: toTimestamp('2022-09-18T19:00:00Z'),
    updatedAt: toTimestamp('2022-09-18T19:00:00Z'),
  },
   {
    id: '11',
    categories: ['prints'],
    translations: {
      fr: { title: "Impression 'Luxembourg en Aquarelle'", description: "Impression de haute qualité d'une peinture à l'aquarelle de la vieille ville de Luxembourg.", materials: "Papier d'art texturé" },
      en: { title: "'Luxembourg in Watercolor' Print", description: "High-quality print of a watercolor painting of Luxembourg's old town.", materials: "Textured fine art paper" },
      de: { title: "'Luxemburg in Aquarell' Druck", description: "Hochwertiger Druck eines Aquarellgemäldes der Altstadt von Luxemburg.", materials: "Strukturiertes Fine Art Papier" },
      pt: { title: "Impressão 'Luxemburgo em Aquarela'", description: "Impressão de alta qualidade de uma pintura em aquarela da cidade velha de Luxemburgo.", materials: "Papel de arte texturizado" },
    },
    cover_original: 'https://picsum.photos/id/1041/800/800',
    cover_thumb: 'https://picsum.photos/id/1041/400/400',
    gallery: [{ original: 'https://picsum.photos/id/1041/800/800', thumb: 'https://picsum.photos/id/1041/400/400', alt: 'Watercolor print of Luxembourg' }],
    priceCents: 18000,
    currency: 'EUR',
    dimensions: { heightCm: 40, widthCm: 50 },
    weightKg: 0.8,
    status: 'available',
    stock: 100,
    isActive: true,
    tags: ['print', 'luxembourg', 'watercolor', 'cityscape'],
    slug: 'luxembourg-in-watercolor-print',
    featured: false,
    createdAt: toTimestamp('2023-06-11T12:00:00Z'),
    updatedAt: toTimestamp('2023-06-11T12:00:00Z'),
  },
  {
    id: '12',
    categories: ['paintings'],
    translations: {
      fr: { title: "Danse Chromatique", description: "Une explosion vibrante de couleurs dans un style d'expressionnisme abstrait.", materials: "Acrylique et encre sur toile" },
      en: { title: "Chromatic Dance", description: "A vibrant explosion of colors in an abstract expressionist style.", materials: "Acrylic and ink on canvas" },
      de: { title: "Chromatischer Tanz", description: "Eine lebendige Farbexplosion im Stil des abstrakten Expressionismus.", materials: "Acryl und Tinte auf Leinwand" },
      pt: { title: "Dança Cromática", description: "Uma explosão vibrante de cores em um estilo expressionista abstrato.", materials: "Acrílico e tinta sobre tela" },
    },
    cover_original: 'https://picsum.photos/id/1074/800/800',
    cover_thumb: 'https://picsum.photos/id/1074/400/400',
    gallery: [{ original: 'https://picsum.photos/id/1074/800/800', thumb: 'https://picsum.photos/id/1074/400/400', alt: 'Vibrant abstract painting' }],
    priceCents: 250000,
    currency: 'EUR',
    dimensions: { heightCm: 150, widthCm: 100, depthCm: 5 },
    weightKg: 10,
    status: 'available',
    stock: 1,
    isActive: true,
    tags: ['large', 'colorful', 'abstract', 'expressionism'],
    slug: 'chromatic-dance',
    featured: true,
    createdAt: toTimestamp('2024-05-01T17:00:00Z'),
    updatedAt: toTimestamp('2024-05-01T17:00:00Z'),
  }
];

const mockAddress1 = {
    userId: 'mock-user-id',
    name: 'John Doe',
    line1: '123 Art Street',
    city: 'Luxembourg',
    postalCode: 'L-1234',
    country: 'Luxembourg',
    phone: '+352 123 456 789',
    isDefault: true,
};

const mockAddress2 = {
    userId: 'mock-user-id',
    name: 'Jane Smith',
    line1: '456 Culture Avenue',
    city: 'Paris',
    postalCode: '75001',
    country: 'France',
    phone: '+33 1 23 45 67 89',
    isDefault: false,
};

export const mockOrders: Order[] = [
    {
        id: '1',
        orderNumber: '1001',
        userId: 'mock-user-id',
        status: 'delivered',
        items: [
            {
                productId: '1',
                title: 'Ethereal Reverie',
                image_thumb: 'https://picsum.photos/id/101/800/800',
                qty: 1,
                priceCents: 120000,
                currency: 'EUR'
            }
        ],
        totals: { subtotalCents: 120000, shippingCents: 2500, discountCents: 0, taxCents: 24500, totalCents: 147000, currency: 'EUR' },
        shippingAddress: mockAddress1,
        billingAddress: mockAddress1,
        payment: { method: 'card', status: 'paid' },
        timeline: [
            { status: 'created', at: toTimestamp('2024-05-10T10:00:00Z') },
            { status: 'paid', at: toTimestamp('2024-05-10T10:05:00Z') },
            { status: 'processing', at: toTimestamp('2024-05-11T14:00:00Z') },
            { status: 'shipped', at: toTimestamp('2024-05-12T09:00:00Z') },
            { status: 'delivered', at: toTimestamp('2024-05-14T11:30:00Z') }
        ],
        createdAt: toTimestamp('2024-05-10T10:00:00Z'),
        updatedAt: toTimestamp('2024-05-14T11:30:00Z'),
    },
    {
        id: '2',
        orderNumber: '1002',
        userId: 'mock-user-id',
        status: 'shipped',
        items: [
            {
                productId: '2',
                title: 'Moon-drop Pendant',
                image_thumb: 'https://picsum.photos/id/201/800/800',
                qty: 1,
                priceCents: 35000,
                currency: 'EUR'
            },
            {
                productId: '6',
                title: "'Echo' Print",
                image_thumb: 'https://picsum.photos/id/604/800/800',
                qty: 2,
                priceCents: 25000,
                currency: 'EUR'
            }
        ],
        totals: { subtotalCents: 85000, shippingCents: 1500, discountCents: 5000, taxCents: 16000, totalCents: 97500, currency: 'EUR' },
        shippingAddress: mockAddress2,
        billingAddress: mockAddress2,
        payment: { method: 'pix', status: 'paid' },
        timeline: [
            { status: 'created', at: toTimestamp('2024-06-20T18:30:00Z') },
            { status: 'paid', at: toTimestamp('2024-06-20T18:32:00Z') },
            { status: 'processing', at: toTimestamp('2024-06-21T10:00:00Z') },
            { status: 'shipped', at: toTimestamp('2024-06-21T16:45:00Z') }
        ],
        createdAt: toTimestamp('2024-06-20T18:30:00Z'),
        updatedAt: toTimestamp('2024-06-21T16:45:00Z'),
    }
];

export let mockAddresses: AddressWithId[] = [
    {
        id: 'addr-1',
        userId: 'mock-user-id',
        name: 'John Doe',
        line1: '123 Art Street',
        city: 'Luxembourg',
        postalCode: 'L-1234',
        country: 'Luxembourg',
        phone: '+352 123 456 789',
        isDefault: true,
    },
    {
        id: 'addr-2',
        userId: 'mock-user-id',
        name: 'John Doe',
        company: 'Art Enthusiasts Inc.',
        line1: '456 Culture Avenue',
        city: 'Paris',
        postalCode: '75001',
        country: 'France',
        phone: '+33 1 23 45 67 89',
        isDefault: false,
    },
];

export let mockWishlist: Wishlist = {
    userId: 'mock-user-id',
    items: [
        { productId: '5', addedAt: toTimestamp('2024-06-15T10:00:00Z') },
        { productId: '7', addedAt: toTimestamp('2024-06-18T14:30:00Z') },
    ]
};