import { Product, Order, AddressWithId, Wishlist } from '../types';

// Este arquivo simula seu banco de dados (Firestore).
// Criamos uma lista de produtos de exemplo com todos os detalhes, incluindo as traduções.
// Usamos isso para desenvolver e testar a aparência do site sem precisar conectar
// ao Firebase o tempo todo. As imagens são placeholders do serviço picsum.photos.

export const mockProducts: Product[] = [
  {
    id: '1',
    sku: 'MP-P-001',
    category: 'paintings',
    translations: {
      fr: { title: "Rêverie Éthérée", description: "Une exploration abstraite des paysages de rêve, mêlant des bleus profonds et des ors scintillants.", materials: "Huile sur toile" },
      en: { title: "Ethereal Reverie", description: "An abstract exploration of dreamscapes, blending deep blues and shimmering golds.", materials: "Oil on canvas" },
      de: { title: "Ätherische Träumerei", description: "Eine abstrakte Erforschung von Traumlandschaften, die tiefe Blautöne und schimmernde Goldtöne mischt.", materials: "Öl auf Leinwand" },
      pt: { title: "Devaneio Etéreo", description: "Uma exploração abstrata de paisagens oníricas, misturando azuis profundos e dourados cintilantes.", materials: "Óleo sobre tela" },
    },
    images: [{ url: 'https://picsum.photos/id/101/800/800', alt: 'Abstract painting with blue and gold', order: 1 }],
    price: { amount: 1200, currency: 'EUR' },
    dimensions: { height: 100, width: 70, depth: 4 },
    weight: 5,
    yearCreated: 2023,
    status: 'available',
    stock: 1,
    certificateOfAuthenticity: true,
    tags: ['abstract', 'blue', 'gold', 'large'],
    slug: 'ethereal-reverie',
    featured: true,
    views: 1250,
    createdAt: '2023-10-26T10:00:00Z',
    updatedAt: '2023-10-26T10:00:00Z',
  },
  {
    id: '2',
    sku: 'MP-J-001',
    category: 'jewelry',
    translations: {
      fr: { title: "Pendentif 'Goutte de Lune'", description: "Un pendentif en argent sterling fait main avec une pierre de lune captivante.", materials: "Argent sterling, pierre de lune" },
      en: { title: "Moon-drop Pendant", description: "A handmade sterling silver pendant featuring a captivating moonstone.", materials: "Sterling silver, moonstone" },
      de: { title: "Mondtropfen-Anhänger", description: "Ein handgefertigter Anhänger aus Sterlingsilber mit einem faszinierenden Mondstein.", materials: "Sterlingsilber, Mondstein" },
      pt: { title: "Pingente Gota de Lua", description: "Um pingente de prata esterlina feito à mão com uma pedra da lua cativante.", materials: "Prata de lei, pedra da lua" },
    },
    images: [{ url: 'https://picsum.photos/id/201/800/800', alt: 'Silver pendant with a moonstone', order: 1 }],
    price: { amount: 350, currency: 'EUR' },
    dimensions: { height: 4, width: 2, depth: 1 },
    weight: 0.1,
    yearCreated: 2024,
    status: 'available',
    stock: 5,
    certificateOfAuthenticity: true,
    tags: ['jewelry', 'silver', 'moonstone', 'handmade'],
    slug: 'moon-drop-pendant',
    featured: true,
    views: 2300,
    createdAt: '2024-01-15T14:30:00Z',
    updatedAt: '2024-01-15T14:30:00Z',
  },
  {
    id: '3',
    sku: 'MP-D-001',
    category: 'digital',
    translations: {
      fr: { title: "Néobloom Cybernétique", description: "Une pièce d'art numérique explorant la fusion de la nature et de la technologie.", materials: "Art numérique, impression giclée" },
      en: { title: "Cybernetic Neobloom", description: "A digital art piece exploring the fusion of nature and technology.", materials: "Digital art, giclée print" },
      de: { title: "Kybernetische Neublüte", description: "Ein digitales Kunstwerk, das die Verschmelzung von Natur und Technologie erforscht.", materials: "Digitale Kunst, Giclée-Druck" },
      pt: { title: "Neoflora Cibernética", description: "Uma peça de arte digital que explora a fusão da natureza com a tecnologia.", materials: "Arte digital, impressão giclée" },
    },
    images: [{ url: 'https://picsum.photos/id/301/800/800', alt: 'Digital art of a futuristic flower', order: 1 }],
    price: { amount: 500, currency: 'EUR' },
    dimensions: { height: 80, width: 80 },
    weight: 2,
    yearCreated: 2024,
    status: 'made-to-order',
    stock: 100,
    certificateOfAuthenticity: true,
    tags: ['digital', 'futuristic', 'nature', 'colorful'],
    slug: 'cybernetic-neobloom',
    featured: true,
    views: 980,
    createdAt: '2024-02-20T11:00:00Z',
    updatedAt: '2024-02-20T11:00:00Z',
  },
  {
    id: '4',
    sku: 'MP-P-002',
    category: 'paintings',
    translations: {
      fr: { title: "Sérénité Urbaine", description: "Paysage urbain abstrait au crépuscule, capturant le calme au milieu du chaos.", materials: "Acrylique sur toile" },
      en: { title: "Urban Serenity", description: "Abstract cityscape at dusk, capturing the calm amidst the chaos.", materials: "Acrylic on canvas" },
      de: { title: "Urbane Gelassenheit", description: "Abstrakte Stadtlandschaft in der Dämmerung, die die Ruhe inmitten des Chaos einfängt.", materials: "Acryl auf Leinwand" },
      pt: { title: "Serenidade Urbana", description: "Paisagem urbana abstrata ao entardecer, capturando a calma em meio ao caos.", materials: "Acrílico sobre tela" },
    },
    images: [{ url: 'https://picsum.photos/id/402/800/800', alt: 'Abstract cityscape painting', order: 1 }],
    price: { amount: 950, currency: 'EUR' },
    dimensions: { height: 60, width: 90, depth: 3 },
    weight: 4,
    yearCreated: 2022,
    status: 'sold',
    stock: 0,
    certificateOfAuthenticity: true,
    tags: ['cityscape', 'abstract', 'dusk', 'acrylic'],
    slug: 'urban-serenity',
    featured: false,
    views: 1500,
    createdAt: '2022-11-05T18:00:00Z',
    updatedAt: '2023-05-10T12:00:00Z',
  },
  {
    id: '5',
    sku: 'MP-P-003',
    category: 'paintings',
    translations: {
      fr: { title: "Murmures de la Forêt", description: "Une peinture texturée représentant la lumière filtrant à travers une canopée dense.", materials: "Techniques mixtes sur bois" },
      en: { title: "Forest Whispers", description: "A textured painting depicting light filtering through a dense canopy.", materials: "Mixed media on wood panel" },
      de: { title: "Waldgeflüster", description: "Ein strukturiertes Gemälde, das Licht darstellt, das durch ein dichtes Blätterdach filtert.", materials: "Mischtechnik auf Holz" },
      pt: { title: "Sussurros da Floresta", description: "Uma pintura texturizada que retrata a luz filtrando através de um denso dossel.", materials: "Técnica mista em painel de madeira" },
    },
    images: [{ url: 'https://picsum.photos/id/503/800/800', alt: 'Painting of a forest canopy', order: 1 }],
    price: { amount: 1500, currency: 'EUR' },
    dimensions: { height: 120, width: 80, depth: 5 },
    weight: 7,
    yearCreated: 2023,
    status: 'available',
    stock: 1,
    certificateOfAuthenticity: true,
    tags: ['forest', 'nature', 'light', 'textured'],
    slug: 'forest-whispers',
    featured: true,
    views: 1800,
    createdAt: '2023-03-12T09:20:00Z',
    updatedAt: '2023-03-12T09:20:00Z',
  },
  {
    id: '6',
    sku: 'MP-PR-001',
    category: 'prints',
    translations: {
      fr: { title: "Impression 'Écho'", description: "Impression giclée en édition limitée de l'œuvre numérique 'Écho'.", materials: "Papier d'art Hahnemühle" },
      en: { title: "'Echo' Print", description: "Limited edition giclée print of the digital artwork 'Echo'.", materials: "Hahnemühle fine art paper" },
      de: { title: "'Echo' Druck", description: "Limitierte Giclée-Druckausgabe des digitalen Kunstwerks 'Echo'.", materials: "Hahnemühle Fine Art Papier" },
      pt: { title: "Impressão 'Eco'", description: "Impressão giclée de edição limitada da obra de arte digital 'Eco'.", materials: "Papel de belas artes Hahnemühle" },
    },
    images: [{ url: 'https://picsum.photos/id/604/800/800', alt: 'Abstract digital art print', order: 1 }],
    price: { amount: 250, currency: 'EUR' },
    dimensions: { height: 50, width: 50 },
    weight: 1,
    yearCreated: 2024,
    status: 'available',
    stock: 50,
    certificateOfAuthenticity: false,
    tags: ['print', 'limited edition', 'giclee', 'abstract'],
    slug: 'echo-print',
    featured: false,
    views: 750,
    createdAt: '2024-03-01T16:45:00Z',
    updatedAt: '2024-03-01T16:45:00Z',
  },
  // Add 6 more products to have 12 total for pagination
    {
    id: '7',
    sku: 'MP-J-002',
    category: 'jewelry',
    translations: {
      fr: { title: "Bague 'Spirale Solaire'", description: "Bague en or 18 carats avec un design en spirale, symbolisant l'énergie éternelle.", materials: "Or 18k" },
      en: { title: "'Solar Spiral' Ring", description: "An 18k gold ring with a spiral design, symbolizing eternal energy.", materials: "18k Gold" },
      de: { title: "'Sonnenspirale' Ring", description: "Ein 18-karätiger Goldring mit Spiraldesign, der ewige Energie symbolisiert.", materials: "18k Gold" },
      pt: { title: "Anel 'Espiral Solar'", description: "Anel em ouro 18k com design em espiral, simbolizando a energia eterna.", materials: "Ouro 18k" },
    },
    images: [{ url: 'https://picsum.photos/id/701/800/800', alt: 'Gold spiral ring', order: 1 }],
    price: { amount: 850, currency: 'EUR' },
    dimensions: { height: 2, width: 2, depth: 0.5 },
    weight: 0.05,
    yearCreated: 2023,
    status: 'available',
    stock: 3,
    certificateOfAuthenticity: true,
    tags: ['jewelry', 'gold', 'ring', 'spiral'],
    slug: 'solar-spiral-ring',
    featured: true,
    views: 3100,
    createdAt: '2023-09-05T10:00:00Z',
    updatedAt: '2023-09-05T10:00:00Z',
  },
  {
    id: '8',
    sku: 'MP-P-004',
    category: 'paintings',
    translations: {
      fr: { title: "Horizon de Corail", description: "Une vue marine semi-abstraite avec des teintes chaudes de corail et de turquoise.", materials: "Aquarelle sur papier" },
      en: { title: "Coral Horizon", description: "A semi-abstract seascape with warm hues of coral and turquoise.", materials: "Watercolor on paper" },
      de: { title: "Korallenhorizont", description: "Eine halbabstrakte Seelandschaft mit warmen Korallen- und Türkistönen.", materials: "Aquarell auf Papier" },
      pt: { title: "Horizonte de Coral", description: "Uma paisagem marinha semi-abstrata com tons quentes de coral e turquesa.", materials: "Aquarela sobre papel" },
    },
    images: [{ url: 'https://picsum.photos/id/802/800/800', alt: 'Watercolor seascape painting', order: 1 }],
    price: { amount: 600, currency: 'EUR' },
    dimensions: { height: 40, width: 60 },
    weight: 1.5,
    yearCreated: 2023,
    status: 'available',
    stock: 1,
    certificateOfAuthenticity: true,
    tags: ['watercolor', 'seascape', 'coral', 'turquoise'],
    slug: 'coral-horizon',
    featured: false,
    views: 900,
    createdAt: '2023-07-21T15:10:00Z',
    updatedAt: '2023-07-21T15:10:00Z',
  },
   {
    id: '9',
    sku: 'MP-D-002',
    category: 'digital',
    translations: {
      fr: { title: "Géométrie Fractale", description: "Composition numérique complexe basée sur des motifs fractals et la géométrie sacrée.", materials: "Art numérique génératif" },
      en: { title: "Fractal Geometry", description: "A complex digital composition based on fractal patterns and sacred geometry.", materials: "Generative digital art" },
      de: { title: "Fraktale Geometrie", description: "Eine komplexe digitale Komposition basierend auf Fraktalmustern und heiliger Geometrie.", materials: "Generative digitale Kunst" },
      pt: { title: "Geometria Fractal", description: "Uma composição digital complexa baseada em padrões fractais e geometria sagrada.", materials: "Arte digital generativa" },
    },
    images: [{ url: 'https://picsum.photos/id/903/800/800', alt: 'Fractal digital art', order: 1 }],
    price: { amount: 450, currency: 'EUR' },
    dimensions: { height: 70, width: 70 },
    weight: 2,
    yearCreated: 2024,
    status: 'made-to-order',
    stock: 100,
    certificateOfAuthenticity: true,
    tags: ['digital', 'fractal', 'geometric', 'abstract'],
    slug: 'fractal-geometry',
    featured: false,
    views: 650,
    createdAt: '2024-04-10T13:00:00Z',
    updatedAt: '2024-04-10T13:00:00Z',
  },
  {
    id: '10',
    sku: 'MP-P-005',
    category: 'paintings',
    translations: {
      fr: { title: "L'Étreinte du Silence", description: "Un portrait minimaliste capturant un moment d'introspection silencieuse.", materials: "Charbon de bois sur papier" },
      en: { title: "The Embrace of Silence", description: "A minimalist portrait capturing a moment of quiet introspection.", materials: "Charcoal on paper" },
      de: { title: "Die Umarmung der Stille", description: "Ein minimalistisches Porträt, das einen Moment stiller Einkehr festhält.", materials: "Kohle auf Papier" },
      pt: { title: "O Abraço do Silêncio", description: "Um retrato minimalista capturando um momento de introspecção silenciosa.", materials: "Carvão sobre papel" },
    },
    images: [{ url: 'https://picsum.photos/id/1011/800/800', alt: 'Charcoal portrait', order: 1 }],
    price: { amount: 750, currency: 'EUR' },
    dimensions: { height: 70, width: 50 },
    weight: 1.8,
    yearCreated: 2022,
    status: 'available',
    stock: 1,
    certificateOfAuthenticity: true,
    tags: ['portrait', 'charcoal', 'minimalist', 'black and white'],
    slug: 'embrace-of-silence',
    featured: true,
    views: 2100,
    createdAt: '2022-09-18T19:00:00Z',
    updatedAt: '2022-09-18T19:00:00Z',
  },
   {
    id: '11',
    sku: 'MP-PR-002',
    category: 'prints',
    translations: {
      fr: { title: "Impression 'Luxembourg en Aquarelle'", description: "Impression de haute qualité d'une peinture à l'aquarelle de la vieille ville de Luxembourg.", materials: "Papier d'art texturé" },
      en: { title: "'Luxembourg in Watercolor' Print", description: "High-quality print of a watercolor painting of Luxembourg's old town.", materials: "Textured fine art paper" },
      de: { title: "'Luxemburg in Aquarell' Druck", description: "Hochwertiger Druck eines Aquarellgemäldes der Altstadt von Luxemburg.", materials: "Strukturiertes Fine Art Papier" },
      pt: { title: "Impressão 'Luxemburgo em Aquarela'", description: "Impressão de alta qualidade de uma pintura em aquarela da cidade velha de Luxemburgo.", materials: "Papel de arte texturizado" },
    },
    images: [{ url: 'https://picsum.photos/id/1041/800/800', alt: 'Watercolor print of Luxembourg', order: 1 }],
    price: { amount: 180, currency: 'EUR' },
    dimensions: { height: 40, width: 50 },
    weight: 0.8,
    yearCreated: 2023,
    status: 'available',
    stock: 100,
    certificateOfAuthenticity: false,
    tags: ['print', 'luxembourg', 'watercolor', 'cityscape'],
    slug: 'luxembourg-in-watercolor-print',
    featured: false,
    views: 1300,
    createdAt: '2023-06-11T12:00:00Z',
    updatedAt: '2023-06-11T12:00:00Z',
  },
  {
    id: '12',
    sku: 'MP-P-006',
    category: 'paintings',
    translations: {
      fr: { title: "Danse Chromatique", description: "Une explosion vibrante de couleurs dans un style d'expressionnisme abstrait.", materials: "Acrylique et encre sur toile" },
      en: { title: "Chromatic Dance", description: "A vibrant explosion of colors in an abstract expressionist style.", materials: "Acrylic and ink on canvas" },
      de: { title: "Chromatischer Tanz", description: "Eine lebendige Farbexplosion im Stil des abstrakten Expressionismus.", materials: "Acryl und Tinte auf Leinwand" },
      pt: { title: "Dança Cromática", description: "Uma explosão vibrante de cores em um estilo expressionista abstrato.", materials: "Acrílico e tinta sobre tela" },
    },
    images: [{ url: 'https://picsum.photos/id/1074/800/800', alt: 'Vibrant abstract painting', order: 1 }],
    price: { amount: 2500, currency: 'EUR' },
    dimensions: { height: 150, width: 100, depth: 5 },
    weight: 10,
    yearCreated: 2024,
    status: 'available',
    stock: 1,
    certificateOfAuthenticity: true,
    tags: ['large', 'colorful', 'abstract', 'expressionism'],
    slug: 'chromatic-dance',
    featured: true,
    views: 450,
    createdAt: '2024-05-01T17:00:00Z',
    updatedAt: '2024-05-01T17:00:00Z',
  }
];

export const mockOrders: Order[] = [
    {
        id: '1',
        orderNumber: '#1001',
        userId: 'mock-user-id',
        status: 'delivered',
        items: [
            {
                productId: '1',
                productSnapshot: { title: 'Ethereal Reverie', image: 'https://picsum.photos/id/101/800/800', price: 1200 },
                quantity: 1,
                price: 1200,
                subtotal: 1200
            }
        ],
        pricing: { subtotal: 1200, shipping: 25, discount: 0, tax: 245, total: 1470 },
        shippingAddress: {
            recipientName: 'John Doe',
            addressLine1: '123 Art Street',
            city: 'Luxembourg',
            postalCode: 'L-1234',
            country: 'Luxembourg',
            phone: '+352 123 456 789',
            isDefault: true,
        },
        paymentMethod: { type: 'card', last4: '4242', brand: 'Visa' },
        paymentStatus: 'paid',
        statusHistory: [
            { status: 'pending', timestamp: '2024-05-10T10:00:00Z' },
            { status: 'confirmed', timestamp: '2024-05-10T10:05:00Z' },
            { status: 'preparing', timestamp: '2024-05-11T14:00:00Z' },
            { status: 'shipped', timestamp: '2024-05-12T09:00:00Z' },
            { status: 'delivered', timestamp: '2024-05-14T11:30:00Z' }
        ],
        createdAt: '2024-05-10T10:00:00Z',
        updatedAt: '2024-05-14T11:30:00Z',
    },
    {
        id: '2',
        orderNumber: '#1002',
        userId: 'mock-user-id',
        status: 'shipped',
        items: [
            {
                productId: '2',
                productSnapshot: { title: 'Moon-drop Pendant', image: 'https://picsum.photos/id/201/800/800', price: 350 },
                quantity: 1,
                price: 350,
                subtotal: 350
            },
            {
                productId: '6',
                productSnapshot: { title: "'Echo' Print", image: 'https://picsum.photos/id/604/800/800', price: 250 },
                quantity: 2,
                price: 250,
                subtotal: 500
            }
        ],
        pricing: { subtotal: 850, shipping: 15, discount: 50, tax: 160, total: 975 },
        shippingAddress: {
            recipientName: 'Jane Smith',
            addressLine1: '456 Culture Avenue',
            city: 'Paris',
            postalCode: '75001',
            country: 'France',
            phone: '+33 1 23 45 67 89',
            isDefault: false,
        },
        paymentMethod: { type: 'paypal' },
        paymentStatus: 'paid',
        statusHistory: [
            { status: 'pending', timestamp: '2024-06-20T18:30:00Z' },
            { status: 'confirmed', timestamp: '2024-06-20T18:32:00Z' },
            { status: 'preparing', timestamp: '2024-06-21T10:00:00Z' },
            { status: 'shipped', timestamp: '2024-06-21T16:45:00Z' }
        ],
        createdAt: '2024-06-20T18:30:00Z',
        updatedAt: '2024-06-21T16:45:00Z',
    }
];

export let mockAddresses: AddressWithId[] = [
    {
        id: 'addr-1',
        recipientName: 'John Doe',
        addressLine1: '123 Art Street',
        city: 'Luxembourg',
        postalCode: 'L-1234',
        country: 'Luxembourg',
        phone: '+352 123 456 789',
        isDefault: true,
    },
    {
        id: 'addr-2',
        recipientName: 'John Doe',
        company: 'Art Enthusiasts Inc.',
        addressLine1: '456 Culture Avenue',
        city: 'Paris',
        postalCode: '75001',
        country: 'France',
        phone: '+33 1 23 45 67 89',
        isDefault: false,
    },
];

export let mockWishlist: Wishlist = {
    userId: 'mock-user-id',
    items: [
        { productId: '5', addedAt: '2024-06-15T10:00:00Z' },
        { productId: '7', addedAt: '2024-06-18T14:30:00Z' },
    ]
};